# Generated by Django 4.2.8 on 2024-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='categories', to='movies.movie'),
        ),
    ]
