# Generated by Django 4.2.8 on 2024-05-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='movie',
            new_name='movies',
        ),
    ]
