# Generated by Django 4.2.8 on 2024-05-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.ImageField(blank=True, default='profile_img.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
